deployment:
  tasks:
    - export DEPLOYPATH=/home/escalas2/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    
deployment:
  tasks:
    - export DEPLOYPATH=/home/escalas2/public_html/
    - /bin/cp -R html $DEPLOYPATH

deployment:
  tasks:
    - export DEPLOYPATH=/home/escalas2/public_html/
    - /bin/cp -R php $DEPLOYPATH